apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:V1
        args:
          - "ignore-db-dir=lost+found"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: vprodb-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-passwd
      nodeSelector:
        zone: eu-north-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-02be24b97611502c4
            fsType: ext4